language: python
python:
  - "2.7"
  - "3.3"
# command to run tests
script: "nosetests -v"
install:
  - pip install -r requirements.txt
  - pip install flake8 --use-mirrors
before_script:
  - flake8 .
